# Your name and what you do
name: Bastien Nony
bio: PhD Student

description: Bastien Nony's Personal Website

# Profile picture
picture: assets/images/favicon/profile_cropped.jpg

# your url: http://USERNAME.github.io
url: https://bastiennony.github.io

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
#twitter: mytwitter
linkedin: https://www.linkedin.com/in/bastien-nony/
github: https://github.com/bastiennony
email: bastien.nony@cerfacs.fr

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: false

# add your skills here
#skills-list:
#    - HTML, Jade
#    - CSS (Stylus, Sass, Less)

research: true

#research-description: The objective of my PhD is to give access to high-fidelity responses of atmospheric pollutant dispersion over complex terrain (in urban areas for instance) and represent associated uncertainties in the event of accidental dispersion.
#<iframe width="560" height="315" src="https://www.youtube.com/embed/K7Xd3XjwL3I" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

research-list:
    Conference:
        name: Conference papers and abstracts
        description: HARMO, 2021, Compound parametric metamodelling of large-eddy simulations for microscale atmospheric dispersion. PDF, Slides

#MascotNum Annual Conference, 2021, Metamodelling for micro-scale atmospheric pollutant dispersion large-eddy simulation. Abstract

teaching: true

teaching-list:
    proba_stats:
        name: Probability & statistics
    markov_chains:
        name: Markov Chains
    an_optim:
        name: Numerical Analysis & Optimization

# do you want to display a projects section? true or false
projects: false

# add your projects here
#project-list:
#    Eve:
#        name: Eve
#        description: Ultra Minimal Single-page Jekyll Template for Building Personal Portfolio Websites
#        url: https://github.com/jibolash/Eve

contact: true

# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
